[package]
name = "nirmoka-adapter-ncdu"
description = "ncdu backend adapter. The cross-platform baseline for Nirmoka."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
nirmoka-adapter = { workspace = true }
nirmoka-core = { workspace = true }
